# Configuration pour différents environnements

LineWorld:
  states: [0, 1, 2, 3, 4]
  actions: [0, 1]
  rewards: [-1, 0, 1]
  terminals: [0, 4]

GridWorld:
  states: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
          16, 17, 18, 19, 20, 21, 22, 23, 24]
  actions: [1, 2, 3, 4] # Left, Right, Down, Up
  rewards: [-1, 0, 1] # (0,0), any other position, (4,4)
  terminals: [0, 1, 2, 3, 4, 5, 9, 10, 14, 15, 18, 19, 20, 21, 22, 23, 24] # lost, win

OtherEnvironment:
  states: [...]
  actions: [...]
  rewards: [...]
  terminals: [...]
